services:
  webcal:
    build: .
    ports:
      - "80:80"
    depends_on:
      - webcal-db
    environment:
      - MYSQL_HOST=webcal-db
      - MYSQL_USER=webcal-user
      - MYSQL_PASSWORD=webcal-password
      - MYSQL_DATABASE=webcal
      - MYSQL_ROOT_PASSWORD=root-password
      - MARIADB_AUTO_UPGRADE=1
      - SMTP_HOST=smtp.server.somewhere
      - SMTP_PORT=my-port
      - SMTP_AUTH=true
      - SMTP_USERNAME=address@some.where
      - SMTP_PASSWORD=address-password

  webcal-db:
    image: mariadb:10.11
    ports:
      - "3306:3306"
    environment:
      - MYSQL_HOST=webcal-db
      - MYSQL_USER=webcal-user
      - MYSQL_PASSWORD=webcal-password
      - MYSQL_DATABASE=webcal
      - MYSQL_ROOT_PASSWORD=root-password
      - MARIADB_AUTO_UPGRADE=1
      - SMTP_HOST=smtp.server.somewhere
      - SMTP_PORT=my-port
      - SMTP_AUTH=true
      - SMTP_USERNAME=address@some.where
      - SMTP_PASSWORD=address-password
